const areas = {
    "Tecnología": [
        "Desarrollo Web",
        "Inteligencia Artificial",
        "Ciberseguridad",
        "Big Data",
        "Desarrollo de Software",
        "Computación en la Nube",
        "Blockchain",
        "Redes y Telecomunicaciones",
        "IoT (Internet de las Cosas)"
    ],
    "Salud": [
        "Medicina General",
        "Enfermería",
        "Odontología",
        "Farmacia",
        "Psicología",
        "Fisioterapia",
        "Nutrición",
        "Laboratorio Clínico",
        "Terapia Ocupacional",
        "Veterinaria"
    ],
    "Educación": [
        "Profesor de Primaria",
        "Profesor de Secundaria",
        "Educación Especial",
        "Psicopedagogía",
        "Educación Infantil",
        "Educación Física",
        "Lengua y Literatura",
        "Matemáticas",
        "Ciencias Sociales",
        "Tecnología Educativa"
    ],
    "Finanzas": [
        "Contabilidad",
        "Auditoría",
        "Banca",
        "Inversiones",
        "Asesoría Financiera",
        "Gestión de Riesgos",
        "Economía",
        "Mercados Financieros",
        "Planificación Financiera",
        "Finanzas Corporativas"
    ],
    "Marketing": [
        "SEO",
        "Publicidad Digital",
        "Marketing de Contenidos",
        "Gestión de Marca",
        "Publicidad en Redes Sociales",
        "Email Marketing",
        "Marketing de Influencers",
        "Investigación de Mercado",
        "Branding",
        "Marketing de Producto"
    ],
    "Derecho": [
        "Derecho Penal",
        "Derecho Civil",
        "Derecho Laboral",
        "Derecho Mercantil",
        "Derecho Constitucional",
        "Derecho Internacional",
        "Derecho Administrativo",
        "Derecho de Familia",
        "Derecho Ambiental",
        "Derecho Tributario"
    ],
    "Arte y Diseño": [
        "Diseño Gráfico",
        "Diseño de Interiores",
        "Arquitectura",
        "Diseño Industrial",
        "Fotografía",
        "Ilustración",
        "Animación",
        "Moda",
        "Arte Digital",
        "Escultura"
    ],
    "Ciencias Sociales": [
        "Sociología",
        "Antropología",
        "Trabajo Social",
        "Ciencias Políticas",
        "Historia",
        "Psicología Social",
        "Geografía Humana",
        "Educación Social",
        "Derechos Humanos",
        "Investigación Social"
    ],
    "Ciencias Naturales": [
        "Biología",
        "Química",
        "Física",
        "Geología",
        "Astronomía",
        "Ecología",
        "Botánica",
        "Zoología",
        "Genética",
        "Biotecnología"
    ],
    "Turismo y Hotelería": [
        "Gestión Hotelera",
        "Turismo Sostenible",
        "Marketing Turístico",
        "Agencias de Viaje",
        "Gestión de Eventos",
        "Planificación Turística",
        "Guía de Turismo",
        "Gastronomía",
        "Gestión de Restaurantes",
        "Cultura y Patrimonio"
    ],
    "Deportes": [
        "Entrenador Deportivo",
        "Fisiología del Ejercicio",
        "Nutrición Deportiva",
        "Psicología Deportiva",
        "Fútbol",
        "Baloncesto",
        "Atletismo",
        "Deportes Acuáticos",
        "Gimnasia",
        "Ciclismo"
    ],
    "Industria y Producción": [
        "Gestión de la Producción",
        "Ingeniería Industrial",
        "Gestión de Calidad",
        "Automatización y Control",
        "Logística",
        "Mantenimiento Industrial",
        "Sostenibilidad Industrial",
        "Fabricación de Productos",
        "Ingeniería de Procesos",
        "Gestión de Proyectos"
    ],
    "Recursos Humanos": [
        "Reclutamiento y Selección",
        "Desarrollo Organizacional",
        "Gestión del Talento Humano",
        "Compensación y Beneficios",
        "Capacitación y Formación",
        "Gestión del Clima Laboral",
        "Bienestar Corporativo",
        "Administración de Personal",
        "Gestión de Desempeño",
        "Responsabilidad Social Empresarial"
    ]
};